### ISSUE TITLE
Error report: The maximum number of attempts has been reached

### ISSUE THREAD

**Issue by cowlike** [notable/notable#1012]
I don't know what this means but it popped up the issue window with this info in it when I was trying to import my `enex` file from an Evernote export

- **OS Version**: darwin 10.14.6
- **Notable Version**: v1.8.3

```
Error: The maximum number of attempts has been reached
    at attempt (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.js:2:176982)
    at file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.js:2:177247
    at FSReqCallback.oncomplete (fs.js:153:23)
```

**Comment by fabiospampinato** [comment]
@cowlike a workaround for this would be to export your Evernote notes in smaller chunks, i.e. multiple smaller .enex files rather than a massive big one, and then import those individually.

In order to address this I need some more info:

- How much does the enex file you tried to import weigh?
- How many notes were you importing?
- How many notes did actually get imported before the issue occurred?

**Comment by cowlike** [comment]
I'll repeat using smaller chunks. I already successfully imported around 800 notes but didn't go back to get the rest of them yet.

* enex file is 354M
* 3787 notes
* 1124, I think (see below)

When I first did this yesterday, I thought it was taking forever so I just killed the process after several hours. Today I blew away the `.notable` folder and decided to watch it as it filled the `notes` subfolder and saw this:

```
$ while true; do ls notes |wc -l; sleep 3; done
     785
     818
     874
     993
    1125
    1125
    1125
    [repeats 1125]
```

**Comment by fabiospampinato** [comment]
> [edit] Something else that occurs to me, a progress bar would be useful. On first use I wasn't sure what was happening when it was apparently just stuck for hours.

Yeah totally: #674 

I've recently improved the situation regarding importing lots of notes in v1.8.3, but apparently not enough, I'll check again if I've missed anything. 

It'd be useful if you could tell me how long precisely it took the app to reach 1125 imported notes.

**Comment by cowlike** [comment]
Sure, see below. I do have to more feedback. I tried smaller chunks (1000 and 600 at a time) but even with the smaller chunks it stopped at 1125.

```
$ while true; do echo "`date` : `ls .notable/notes |wc -l`"; sleep 3; done
Mon Jan 20 09:46:11 CST 2020 :        0
Mon Jan 20 09:46:14 CST 2020 :        0
Mon Jan 20 09:46:17 CST 2020 :        0
Mon Jan 20 09:46:20 CST 2020 :       39
Mon Jan 20 09:46:23 CST 2020 :      138
Mon Jan 20 09:46:26 CST 2020 :      213
Mon Jan 20 09:46:29 CST 2020 :      259
Mon Jan 20 09:46:32 CST 2020 :      334
Mon Jan 20 09:46:35 CST 2020 :      354
Mon Jan 20 09:46:38 CST 2020 :      355
Mon Jan 20 09:46:41 CST 2020 :      383
Mon Jan 20 09:46:44 CST 2020 :      431
Mon Jan 20 09:46:47 CST 2020 :      456
Mon Jan 20 09:46:50 CST 2020 :      497
Mon Jan 20 09:46:53 CST 2020 :      521
Mon Jan 20 09:46:56 CST 2020 :      557
Mon Jan 20 09:46:59 CST 2020 :      602
Mon Jan 20 09:47:02 CST 2020 :      643
Mon Jan 20 09:47:05 CST 2020 :      690
Mon Jan 20 09:47:08 CST 2020 :      725
Mon Jan 20 09:47:11 CST 2020 :      761
Mon Jan 20 09:47:14 CST 2020 :      785
Mon Jan 20 09:47:17 CST 2020 :      785
Mon Jan 20 09:47:20 CST 2020 :      812
Mon Jan 20 09:47:23 CST 2020 :      867
Mon Jan 20 09:47:26 CST 2020 :      986
Mon Jan 20 09:47:30 CST 2020 :     1125
Mon Jan 20 09:47:33 CST 2020 :     1125
Mon Jan 20 09:47:36 CST 2020 :     1125
Mon Jan 20 09:47:39 CST 2020 :     1125
Mon Jan 20 09:47:42 CST 2020 :     1125
Mon Jan 20 09:47:45 CST 2020 :     1125
[repeats]
```

**Comment by fabiospampinato** [comment]
@cowlike So about 90 seconds 🤔 

> I tried smaller chunks (1000 and 600 at a time) but even with the smaller chunks it stopped at 1125.

Interesting 🤔 

I have an idea on how to address this, I might have to push v1.8.4 because of an issue with on Windows anyway, I'll see if I can squeeze the change for this in too.

**Comment by fabiospampinato** [comment]
Alright I can reproduce, "definitive" fix coming in v1.8.4, although the app will still appear frozen while it's importing notes, I'll fix that later.

**Comment by cowlike** [comment]
Nice.  Look forward to trying it.

**Comment by cowlike** [comment]
Sorry but it's still not fixed. I have no idea what is going on with my enex file but it is failing to import on both the MacOS and Linux versions using 1.8.4. When I import on MacOS it keeps looping forever when I have 1125 files in the notes folder. On Linux it got stuck at 1126. Is there any log that can be enabled to get more details?

**Comment by fabiospampinato** [comment]
Oh really?! Are you still getting the "The maximum number of attempts has been reached" error?

There's no logs to take a look at.

**Comment by cowlike** [comment]
In the last iterations I've been trying, I killed the process and removed the `~/.notable` folder. I believe that error happened after I killed the process and just restarted the import again without removing any files. I'll try that again now... No, that's not happening. If I just kill the processes and restart the import without removing any files, the file count increases a bit and gets stuck again. I don't know if it's reimporting the same notes before getting stuck or what.

**Comment by cowlike** [comment]
Update:

By dumb luck, I was looking through the list of notes and deleted some duplicate names. I deleted about 10 notes out of 3787 total and exported a new enex file. The new file imported successfully. 

At this point I have no idea what the actual bug is and there probably isn't enough information here for you to find it. You might want to have some sort of debug logging facility to help if such a thing pops up again but I guess you'll probably want to close this for now.

**Comment by fabiospampinato** [comment]
@cowlike that's pretty interesting. Could you check if importing just those 10 notes, perhaps in an empty data directory, triggers the issue? Also would it be possible for you to send me at fabio@notable.md those notes or similar notes (like I don't think the actual content of those notes matters) that still reproduce the issue?

**Comment by cowlike** [comment]
Yes I can see if I can find them again. I have the original enex file but unfortunately I wiped out my Evernote garbage so I don't know right now exactly what I deleted. I'm pretty sure I can repro it though but just not right now. I'll get back to you.
