### ISSUE TITLE
Error report: These sources are not supported: /home/chr1s/Workspace/github/programming-notes

### ISSUE THREAD

**Issue by chr1sgong** [notable/notable#1301]
- **OS Version**: linux 5.7.17-2-MANJARO
- **Notable Version**: v1.8.4

```
Error: These sources are not supported: /home/chr1s/Workspace/github/programming-notes
    at Object.dump (file:///opt/Notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:201495)
    at import_Import.import (file:///opt/Notable/resources/app.asar/renderer/renderer.js:2:24295)
```

**Comment by fabiospampinato** [comment]
What kind of file where you trying to import?
