### ISSUE TITLE
Error report: File too large, try splitting it into smaller ones

### ISSUE THREAD

**Issue by crumbletop** [notable/notable#1341]
- **OS Version**: darwin 10.13.6
- **Notable Version**: v1.8.4

```
Error: File too large, try splitting it into smaller ones
    at file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:1768
    at async Object.read (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:1849)
    at async EnexProvider.dump (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:3392)
    at async Object.dump (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:201681)
    at async import_Import.import (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.js:2:24287)
```

**Comment by fabiospampinato** [comment]
You should do that, export your notes in smaller batches and then import the batches one by one.

**Comment by crumbletop** [comment]
Thanks.  Will do.  My apologies for the report.

On Oct 17, 2020, at 11:57 AM, Fabio Spampinato <notifications@github.com<mailto:notifications@github.com>> wrote:



You should do that, export your notes in smaller batches and then import the batches one by one.

**Comment by fabiospampinato** [comment]
Thank you for the report, it's useful to me to learn that people are are actually encountering these issues and how often.

**Comment by fabiospampinato** [comment]
I'm closing this as there's an issue tracking potentially handling arbitrarily-sized files already.
