### ISSUE TITLE
Error report: Model is disposed!

### ISSUE THREAD

**Issue by apettenati** [notable/notable#1414]
- **OS Version**: win32 10.0.18363
- **Notable Version**: v1.9.0-alpha.19

```
Error: Model is disposed!
    at t._assertNotDisposed (file:///C:/Users/Amanda/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.80dc09ab8c24f08beeee.js:1:401729)
    at t.getOptions (file:///C:/Users/Amanda/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.80dc09ab8c24f08beeee.js:1:404894)
    at Object.initEditor (file:///C:/Users/Amanda/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.55977bf6113fea47d1d7.js:1:1219)
    at Object.init (file:///C:/Users/Amanda/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.55977bf6113fea47d1d7.js:1:296)
    at file:///C:/Users/Amanda/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.55977bf6113fea47d1d7.js:1:6592
    at is (file:///C:/Users/Amanda/AppData/Local/Programs/notable/resources/app.asar/renderer/renderer.js:1:1328313)
    at ml (file:///C:/Users/Amanda/AppData/Local/Programs/notable/resources/app.asar/renderer/renderer.js:1:1347392)
    at t.unstable_runWithPriority (file:///C:/Users/Amanda/AppData/Local/Programs/notable/resources/app.asar/renderer/renderer.js:1:1365660)
    at qi (file:///C:/Users/Amanda/AppData/Local/Programs/notable/resources/app.asar/renderer/renderer.js:1:1290128)
    at gl (file:///C:/Users/Amanda/AppData/Local/Programs/notable/resources/app.asar/renderer/renderer.js:1:1347151)
    at file:///C:/Users/Amanda/AppData/Local/Programs/notable/resources/app.asar/renderer/renderer.js:1:1347062
    at L (file:///C:/Users/Amanda/AppData/Local/Programs/notable/resources/app.asar/renderer/renderer.js:1:1364599)
    at MessagePort.E.port1.onmessage (file:///C:/Users/Amanda/AppData/Local/Programs/notable/resources/app.asar/renderer/renderer.js:1:1363355)
```

**Comment by fabiospampinato** [comment]
It should be fixed in the beta: https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.0
