### ISSUE TITLE
Error report: e.name.trim is not a function

### ISSUE THREAD

**Issue by zzfnohell** [notable/notable#1417]
- **OS Version**: win32 10.0.19042
- **Notable Version**: v1.8.4

```
TypeError: e.name.trim is not a function
    at EnexAttachment.sanitizeMetadata (file:///D:/Scoop/apps/notable/1.8.4/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:5173)
    at file:///D:/Scoop/apps/notable/1.8.4/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:4913
    at Array.map (<anonymous>)
    at EnexAttachment.get (file:///D:/Scoop/apps/notable/1.8.4/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:4901)
    at async Promise.all (index 0)
    at async EnexNote.getMetadata (file:///D:/Scoop/apps/notable/1.8.4/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:185659)
    at async EnexNote.get (file:///D:/Scoop/apps/notable/1.8.4/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:3578)
    at async EnexProvider.dump (file:///D:/Scoop/apps/notable/1.8.4/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:3469)
    at async Object.dump (file:///D:/Scoop/apps/notable/1.8.4/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:201681)
    at async import_Import.import (file:///D:/Scoop/apps/notable/1.8.4/resources/app.asar/renderer/renderer.js:2:24287)
```

**Comment by fabiospampinato** [comment]
That's fixed in the betas https://github.com/notable/notable-insiders/releases/tag/v1.9.0-beta.1
