### ISSUE TITLE
Math Mode: Global Macros not Always Rendering Correctly

### ISSUE THREAD

**Issue by maximilianreimer** [notable/notable#1472]
- **OS Version**: ManjaroLinux 20.2.1
- **Notable Version**: 1.9.0-beta.1

### Current behavior
See screen shot

### Expected behavior
`$\c$` should be displayed as `$\mathcal{C}$`like in the row where multiple macros are used. 
![grafik](https://user-images.githubusercontent.com/6999824/111452270-a312a000-8712-11eb-968b-54e2a5038389.png)

**Comment by maximilianreimer** [comment]
Update: 

if I add; 
```
$\c$
$$\c$$
$\b, \c, \d, \f, \g, \h, \l, \u, \s$
```
to my note I get the following:
![grafik](https://user-images.githubusercontent.com/6999824/111453335-c2f69380-8713-11eb-92cd-6b6941354346.png)

Here the complete errors for reference: 
For `$$\c$$`: 
```
The KaTeX plugin tried interpreting the following code:

\c
But the following error happened:

ParseError: KaTeX parse error: Undefined control sequence: \c at position 1: \̲c̲
    at new e (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:1:1995)
    at e.r.parseGroup (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:232:36506)
    at e.r.parseAtom (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:232:31213)
    at e.r.parseExpression (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:232:30101)
    at e.r.parse (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:232:29771)
    at l0 (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:233:1893)
    at h0 (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:233:2689)
    at Object.renderToString (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:233:2809)
    at Object.render (file:///opt/Notable/resources/app.asar/renderer/chunk.3817e65420ec95873fb6.js:1:446)
    at async q (file:///opt/Notable/resources/app.asar/renderer/renderer.26c42f1e725abf9e4a12.js:720:19095)
    at async k._execTransform (file:///opt/Notable/resources/app.asar/renderer/renderer.26c42f1e725abf9e4a12.js:62:2176)
    at async renderer (file:///opt/Notable/resources/app.asar/renderer/renderer.26c42f1e725abf9e4a12.js:56:2330)
``` 
And for `$\b, \c, \d, \f, \g, \h, \l, \u, \s$`: 

```
The KaTeX plugin tried interpreting the following code:

\b, \c, \d, \f, \g, \h, \l, \u, \s
But the following error happened:

ParseError: KaTeX parse error: Undefined control sequence: \b at position 1: \̲b̲, \c, \d, \f, \…
    at new e (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:1:1995)
    at e.r.parseGroup (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:232:36506)
    at e.r.parseAtom (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:232:31213)
    at e.r.parseExpression (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:232:30101)
    at e.r.parse (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:232:29771)
    at l0 (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:233:1893)
    at h0 (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:233:2689)
    at Object.renderToString (file:///opt/Notable/resources/app.asar/renderer/chunk.6c42b723b5622cf351c9.js:233:2809)
    at Object.render (file:///opt/Notable/resources/app.asar/renderer/chunk.3817e65420ec95873fb6.js:1:446)
    at async q (file:///opt/Notable/resources/app.asar/renderer/renderer.26c42f1e725abf9e4a12.js:720:19095)
    at async k._execTransform (file:///opt/Notable/resources/app.asar/renderer/renderer.26c42f1e725abf9e4a12.js:62:2176)
    at async renderer (file:///opt/Notable/resources/app.asar/renderer/renderer.26c42f1e725abf9e4a12.js:56:2330)
```

**Comment by fabiospampinato** [comment]
@maximilianreimer macros should be defined in the settings, I think that's the problem you are seeing here maybe 🤔
