### ISSUE TITLE
Error report: These sources are not supported: /local/earejes/gdrive/notable/notes

### ISSUE THREAD

**Issue by jareso76** [notable/notable#1475]
- **OS Version**: linux 3.10.0-1160.15.2.el7.x86_64
- **Notable Version**: v1.8.4-2

```
Error: These sources are not supported: /local/earejes/gdrive/notable/notes
    at Object.dump (file:///var/lib/snapd/snap/notable/3/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:201495)
    at import_Import.import (file:///var/lib/snapd/snap/notable/3/resources/app.asar/renderer/renderer.js:2:25026)
```

**Comment by fabiospampinato** [comment]
@jareso76 What were you trying to import? Like how can I reproduce the issue?
