### ISSUE TITLE
Error report: Loading chunk 1 failed.(missing: file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/chunk.4630e75e309c96529bfc.js)

### ISSUE THREAD

**Issue by RKitSeal** [notable/notable#1582]
- **OS Version**: darwin 11.6.2
- **Notable Version**: v1.9.0-beta.4

```
ChunkLoadError: Loading chunk 1 failed.
(missing: file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/chunk.4630e75e309c96529bfc.js)
    at Function.a.e (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:2:427)
    at loader (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:20:67127)
    at b (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:64:17530)
    at P.constructor (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:20:66986)
    at P.N [as render] (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:9041)
    at R (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:6639)
    at A (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:2712)
    at R (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:6893)
    at A (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:2712)
    at R (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:6893)
    at A (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:2712)
    at R (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:6893)
    at A (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:2712)
    at R (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:6893)
    at A (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:2712)
    at R (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:6893)
    at A (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:2712)
    at R (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:6893)
    at file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:2004
    at Array.some (<anonymous>)
    at x (file:///Applications/Notable-1.9.0-beta.1.app/Contents/Resources/app.asar/renderer/renderer.f12e681e3509d7f8e3cd.js:36:1891)
```

**Comment by RKitSeal** [comment]
![image](https://user-images.githubusercontent.com/79415396/151333144-6c60cac4-82af-43af-83c9-448c531018cb.png)
