### ISSUE TITLE
Mermaid Diagrams Not Generating

### ISSUE THREAD

**Issue by nfantis** [notable/notable#1587]
- **OS Version**: macOS Monterey 12.1
- **Notable Version**: Version 1.9.0-beta.5

### Current behavior

I've tried a few sample diagrams from the Mermaid Live Editor (https://mermaid.live/) in Notable.  These diagrams have worked correctly in previous versions of Notable.  Now an error is being thrown:

```
TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at r (file:///Applications/Notable%201.9%20Beta.app/Contents/Resources/app.asar/renderer/chunk.3b382d6e82f4df72a61b.js:74:8076)
    at file:///Applications/Notable%201.9%20Beta.app/Contents/Resources/app.asar/renderer/chunk.3b382d6e82f4df72a61b.js:1172:2856
    at Array.forEach (<anonymous>)
    at Object.render (file:///Applications/Notable%201.9%20Beta.app/Contents/Resources/app.asar/renderer/chunk.3b382d6e82f4df72a61b.js:1172:2835)
    at Object.svg (file:///Applications/Notable%201.9%20Beta.app/Contents/Resources/app.asar/renderer/chunk.82b02c435f2c3eaaac7e.js:1:949)
    at async Object.render (file:///Applications/Notable%201.9%20Beta.app/Contents/Resources/app.asar/renderer/chunk.82b02c435f2c3eaaac7e.js:1:353)
    at async replace (file:///Applications/Notable%201.9%20Beta.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:1007:24874)
    at async file:///Applications/Notable%201.9%20Beta.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:209:2590
    at async Promise.all (index 1)
    at async x._execTransform (file:///Applications/Notable%201.9%20Beta.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:209:2507)
    at async file:///Applications/Notable%201.9%20Beta.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:203:5445
```
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/22967457/151839287-c90dea75-4352-4ed6-bdc2-16f7bfcc21d9.png">

### How to Reproduce
1. Create a new note.
1. Enter a code block indicating a Mermaid diagram.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/22967457/151838116-ddee6b0e-b69e-4f8d-9724-f5f309498cea.png">

```
sequenceDiagram
    Alice->>+John: Hello John, how are you?
    Alice->>+John: John, can you hear me?
    John-->>-Alice: Hi Alice, I can hear you!
    John-->>-Alice: I feel great!

graph TD
    A[Christmas] -->|Get money| B(Go shopping)
    B --> C{Let me think}
    C -->|One| D[Laptop]
    C -->|Two| E[iPhone]
    C -->|Three| F[fa:fa-car Car]
```

### Expected behavior

The diagram should generate properly:

<img width="347" alt="image" src="https://user-images.githubusercontent.com/22967457/151838760-d93174bb-5274-4bf8-b137-441bc2e3d4dc.png">

<img width="470" alt="image" src="https://user-images.githubusercontent.com/22967457/151838818-c7427856-dd6e-4656-ad8e-e90bdb1f10c4.png">

**Comment by nfantis** [comment]
I have confirmed that this issue is resolved in 1.9.0-beta.6.  Thank you for addressing this!
