### ISSUE TITLE
Error report: Loading chunk 1 failed.(missing: file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.f7f8c6dc869150c870d1.js)

### ISSUE THREAD

**Issue by matthijsvp** [notable/notable#1593]
- **OS Version**: darwin 12.2.1
- **Notable Version**: v1.9.0-beta.5

```
ChunkLoadError: Loading chunk 1 failed.
(missing: file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.f7f8c6dc869150c870d1.js)
    at Function.s.e (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:2:427)
    at loader (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:20:68940)
    at b (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:64:21817)
    at y.constructor (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:20:68799)
    at y.re [as render] (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:9069)
    at I (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:6629)
    at x (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:2711)
    at I (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:6883)
    at x (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:2711)
    at I (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:6883)
    at x (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:2711)
    at I (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:6883)
    at x (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:2711)
    at I (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:6883)
    at x (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:2711)
    at I (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:6883)
    at x (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:2711)
    at I (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:6883)
    at file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:2001
    at Array.some (<anonymous>)
    at M (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.52841b62858b298ec080.js:36:1887)
```

**Comment by MMK21Hub** [comment]
Duplicate of #1582
