### ISSUE TITLE
Error report: Loading chunk 1 failed.(missing: file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.a36cd890d8cd5acb172f.js)

### ISSUE THREAD

**Issue by Serenacula** [notable/notable#1607]
Crash occurred when pressing the edit button.

- **OS Version**: darwin 12.2.1
- **Notable Version**: v1.9.0-beta.7

```
ChunkLoadError: Loading chunk 1 failed.
(missing: file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.a36cd890d8cd5acb172f.js)
    at Function.i.e (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.cd329d27f9aa0f8c42d8.js:2:427)
    at loader (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.cd329d27f9aa0f8c42d8.js:20:69101)
    at b (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.cd329d27f9aa0f8c42d8.js:67:19657)
    at y.constructor (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.cd329d27f9aa0f8c42d8.js:20:68960)
    at y.re [as render] (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.cd329d27f9aa0f8c42d8.js:37:9894)
    at I (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.cd329d27f9aa0f8c42d8.js:37:7456)
    at x (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.cd329d27f9aa0f8c42d8.js:37:3539)
    at I (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.cd329d27f9aa0f8c42d8.js:37:7710)
    at x (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.cd329d27f9aa0f8c42d8.js:37:3539)
    at I (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.cd329d27f9aa0f8c42d8.js:37:7710)
    at x (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.cd329d27f9aa0f8c42d8.js:37:3539)
    at I (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.cd329d27f9aa0f8c42d8.js:37:7710)
    at file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.cd329d27f9aa0f8c42d8.js:37:2829
    at Array.some (<anonymous>)
    at M (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.cd329d27f9aa0f8c42d8.js:37:2715)
```

**Comment by fabiospampinato** [comment]
Do you get this issue consistently, after each time you restart the app?

**Comment by Serenacula** [comment]
I don't, no, it hasn't happened again. I did update after this, so it may have been a one-off thing, or just a beta7 bug, idk.
