### ISSUE TITLE
Error report: These sources are not supported: 

### ISSUE THREAD

**Issue by oteixeiras** [notable/notable#1622]
- **OS Version**: linux 5.18.6-200.fc36.x86_64
- **Notable Version**: v1.8.4

```
Error: These sources are not supported: /home/oteixeiras/Documentos/notes
    at Object.dump (file:///opt/Notable/resources/app.asar/renderer/chunk.801f2cae377ea1944a34.js:2:201495)
    at import_Import.import (file:///opt/Notable/resources/app.asar/renderer/renderer.js:2:24295)
```

**Comment by fabiospampinato** [comment]
What extension do those files you are trying to import have?
