### ISSUE TITLE
Note menu causes an error when window is closed (macOS)

### ISSUE THREAD

**Issue by ljcooke** [notable/notable#499]
- **OS Version**: macOS Mojave 10.14.3
- **Notable Version**: 1.3.0

### Current behavior

An error dialog appears if you use the Note menu while the window is closed.

```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read property 'webContents' of undefined
    at click (/Applications/Notable.app/Contents/Resources/app.asar/webpack:/src/main/windows/main.ts:134:26)
    at MenuItem.click (/Applications/Notable.app/Contents/Resources/electron.asar/browser/api/menu-item.js:56:9)
    at Function.executeCommand (/Applications/Notable.app/Contents/Resources/electron.asar/browser/api/menu.js:31:13)
```

Steps to reproduce:

1. Press Cmd-W to close the window.
2. Select the Note menu, then New.

### Expected behavior

Note > New reopens the window before creating a new note. Other Note menu items are disabled.

**Comment by ljcooke** [comment]
Sorry I missed #416 – looks like this will fix it in the next release.
