### ISSUE TITLE
An error occurred: url.replace is not a function

### ISSUE THREAD

**Issue by jailsonsf** [notable/notable#699]
- **OS Version**: linux 4.19.49-1-MANJARO
- **Notable Version**: v1.5.1

```
TypeError: url.replace is not a function
    at writeAnchorTag (/tmp/.mount_NotablIAASs3/resources/app.asar/node_modules/showdown/dist/showdown.js:2819:15)
    at String.replace (<anonymous>)
    at /tmp/.mount_NotablIAASs3/resources/app.asar/node_modules/showdown/dist/showdown.js:2857:15
    at /tmp/.mount_NotablIAASs3/resources/app.asar/node_modules/showdown/dist/showdown.js:4338:39
    at /tmp/.mount_NotablIAASs3/resources/app.asar/node_modules/showdown/dist/showdown.js:4059:49
    at String.replace (<anonymous>)
    at processListItems (/tmp/.mount_NotablIAASs3/resources/app.asar/node_modules/showdown/dist/showdown.js:4011:23)
    at parseConsecutiveLists (/tmp/.mount_NotablIAASs3/resources/app.asar/node_modules/showdown/dist/showdown.js:4129:53)
    at /tmp/.mount_NotablIAASs3/resources/app.asar/node_modules/showdown/dist/showdown.js:4152:16
    at String.replace (<anonymous>)
```

**Comment by fabiospampinato** [comment]
Sounds like an error with `showdown`, which will be replaced with `markdown-it` in the next release, that probably fixed it already 🤔

**Comment by jailsonsf** [comment]
I understand, in this case I will wait for the next release :+1:
