### ISSUE TITLE
An error occurred: Unexpected identifier

### ISSUE THREAD

**Issue by BarlowTucker** [notable/notable#708]
- **OS Version**: darwin 18.6.0
- **Notable Version**: v1.5.1

```
/Applications/Notable.app/Contents/Resources/app.asar/node_modules/dagre-d3-renderer/lib/label/add-html-label.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { import util from '../util'
                                                                                                                                                                  ^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:85:7)
    at createScript (vm.js:266:10)
    at Object.runInThisContext (vm.js:314:10)
    at Module._compile (internal/modules/cjs/loader.js:742:26)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:820:10)
    at Module.load (internal/modules/cjs/loader.js:677:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:609:12)
    at Function.Module._load (internal/modules/cjs/loader.js:601:3)
    at Module.require (internal/modules/cjs/loader.js:715:19)
    at require (internal/modules/cjs/helpers.js:14:16)
```

**Comment by fabiospampinato** [comment]
🤔 it looks like an issue that originated from Mermaid, any idea how to reproduce this?

**Comment by fabiospampinato** [comment]
@BarlowTucker If you can provide a note that reproduces this issue I'd be happy to reopen it.
