### ISSUE TITLE
An error occurred: $ is not defined

### ISSUE THREAD

**Issue by smofor** [notable/notable#713]
- **OS Version**: darwin 18.6.0
- **Notable Version**: v1.5.1

```
ReferenceError: $ is not defined
    at EditorPlugins.componentWillMount (webpack-internal:///./src/renderer/components/main/extra/editor_plugins.tsx:37:9)
    at callComponentWillMount (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:11422:14)
    at mountClassInstance (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:11515:5)
    at updateClassComponent (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:14689:5)
    at beginWork (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:15645:16)
    at performUnitOfWork (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:19313:12)
    at workLoop (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:19353:24)
    at renderRoot (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:19436:7)
    at performWorkOnRoot (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:20343:7)
    at performWork (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:20255:7)
```

**Comment by fabiospampinato** [comment]
It seems that perhaps a file failed to load, can you reproduce this bug reliably?
