### ISSUE TITLE
An error occurred: e.parser is not a constructor

### ISSUE THREAD

**Issue by rowanu** [notable/notable#774]
Can't import anything from an ENEX file. I'm guessing it's a dependency/version issue, as it doesn't work with a simple text note.

Note (with txt extension) [test1.enex.txt](https://github.com/notable/notable/files/3489845/test1.enex.txt)

- **OS Version**: darwin 18.5.0
- **Notable Version**: v1.7.1

```
TypeError: e.parser is not a constructor
    at htmlParser (file:///Applications/Notable.app/Contents/Resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:39358)
    at new RootNode (file:///Applications/Notable.app/Contents/Resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:39371)
    at TurndownService.turndown (file:///Applications/Notable.app/Contents/Resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:42918)
    at Object.html2markdown [as default] (file:///Applications/Notable.app/Contents/Resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:33523)
    at Object.convert (file:///Applications/Notable.app/Contents/Resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:1939)
    at EnexNote.formatContent (file:///Applications/Notable.app/Contents/Resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:44653)
    at EnexNote.get (file:///Applications/Notable.app/Contents/Resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:2883)
    at async EnexProvider.dump (file:///Applications/Notable.app/Contents/Resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:2706)
    at async Object.dump (file:///Applications/Notable.app/Contents/Resources/app.asar/chunk.b2bf0d0b1d0ebd17b6b3.js:1:57972)
    at async import_Import.import (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer.js:1:21709)
```

**Comment by fabiospampinato** [comment]
My bad, fix coming soon!

**Comment by fabiospampinato** [comment]
I just fixed this, the fix will be available in the next patch release.
