### ISSUE TITLE
An error occurred: Cannot create a string longer than 0x3fffffe7 characters

### ISSUE THREAD

**Issue by BladeSnow** [notable/notable#809]
- **OS Version**: win32 10.0.18362
- **Notable Version**: v1.7.3

```
Error: Cannot create a string longer than 0x3fffffe7 characters
    at Buffer.toString (buffer.js:623:17)
    at EnexProvider.getNotesRaw (file:///C:/Users/%E6%88%BF%E5%AE%81/AppData/Local/Programs/notable/resources/app.asar/chunk.fba3d68ffab26c3d35e8.js:1:43949)
    at EnexProvider.dump (file:///C:/Users/%E6%88%BF%E5%AE%81/AppData/Local/Programs/notable/resources/app.asar/chunk.fba3d68ffab26c3d35e8.js:1:2667)
    at async Object.dump (file:///C:/Users/%E6%88%BF%E5%AE%81/AppData/Local/Programs/notable/resources/app.asar/chunk.fba3d68ffab26c3d35e8.js:1:57993)
    at async import_Import.import (file:///C:/Users/%E6%88%BF%E5%AE%81/AppData/Local/Programs/notable/resources/app.asar/renderer.js:1:21799)
```

**Comment by fabiospampinato** [comment]
It looks like you are importing a huge file, how big is it?
