### ISSUE TITLE
An error occurred: Loading chunk 3 failed.(missing: file:///Applications/Notable.app/Contents/Resources/app.asar/chunk.09acbab64e252f475f2d.js)

### ISSUE THREAD

**Issue by sdwill** [notable/notable#890]
- **OS Version**: darwin 17.7.0
- **Notable Version**: v1.7.3

```
ChunkLoadError: Loading chunk 3 failed.
(missing: file:///Applications/Notable.app/Contents/Resources/app.asar/chunk.09acbab64e252f475f2d.js)
    at Function.requireEnsure [as e] (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer.js:1:3474)
    at loader (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer.js:89:237524)
    at hf (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer.js:50:65998)
    at Tg (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer.js:50:66207)
    at bi (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer.js:50:90698)
    at ci (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer.js:50:91082)
    at Di (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer.js:50:97972)
    at Yh (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer.js:50:97352)
    at Xh (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer.js:50:96373)
    at qf (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer.js:50:95244)
```

**Comment by fabiospampinato** [comment]
Thanks for reporting the issue.

Do you remember what you were doing before this error happened?

**Comment by fabiospampinato** [comment]
That chunk contained the code related to the editor. Is the editor not working for you? Can you reproduce reliably?

I'd say this is most probably kind of a random fluke.

**Comment by Danmou** [comment]
In case it's useful, I was seeing a similar error on Manjaro Linux when trying to view many of my notes:
![Screenshot from 2019-12-04 14-29-09](https://user-images.githubusercontent.com/7031745/70146523-a6f7eb80-16a2-11ea-989e-37724c04f1ed.png)

Restarting Notable fixed it for now. I'll let you know if the problem returns.

**Comment by fabiospampinato** [comment]
@Danmou This is a pretty weird issue, it looks as like there's a chance the app may fail to read files from disk some times 🤔
