### ISSUE TITLE
Error report: File too large, try splitting it into smaller ones

### ISSUE THREAD

**Issue by alexriabtsev** [notable/notable#897]
- **OS Version**: darwin 10.15.2
- **Notable Version**: v1.8.1

```
Error: File too large, try splitting it into smaller ones
    at file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.c5d7fb991b1c794df244.js:1:1229
    at async Object.read (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.c5d7fb991b1c794df244.js:1:1310)
    at async EnexProvider.dump (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.c5d7fb991b1c794df244.js:1:6613)
    at async Object.dump (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/chunk.c5d7fb991b1c794df244.js:1:58984)
    at async import_Import.import (file:///Applications/Notable.app/Contents/Resources/app.asar/renderer/renderer.js:2:22114)
```

**Comment by fabiospampinato** [comment]
Do what it says, you're importing a huge file (>= 1GB), try importing smaller ones instead.
