### ISSUE TITLE
Error report: These sources are not supported: C:\Users\jolemay\AppData\Local\Microsoft\Windows\INetCache\IE\5P014WBE\SkySyncRedir[1].aspx

### ISSUE THREAD

**Issue by JohnLeMay4** [notable/notable#926]
- **OS Version**: win32 10.0.17763
- **Notable Version**: v1.8.1

```
Error: These sources are not supported: C:\Users\jolemay\AppData\Local\Microsoft\Windows\INetCache\IE\5P014WBE\SkySyncRedir[1].aspx
    at Object.dump (file:///C:/Users/jolemay/AppData/Local/Programs/notable/resources/app.asar/renderer/chunk.c5d7fb991b1c794df244.js:1:58798)
    at import_Import.import (file:///C:/Users/jolemay/AppData/Local/Programs/notable/resources/app.asar/renderer/renderer.js:2:22122)
```

**Comment by fabiospampinato** [comment]
Was `C:\Users\jolemay\AppData\Local\Microsoft\Windows\INetCache\IE\5P014WBE\SkySyncRedir[1].aspx` the file you tried importing? If not could you email me at fabio@notable.md the file you tried to import that causes this issue? (or another one with bogus content which still reproduces the issue)
